config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id].to_i)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_security)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id].to_i)
  end

  def update
    @task = Task.find(params[:id].to_i)
    @task.update(task_security)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id].to_i)
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_security
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title%>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% i = 0 %>
<% @tasks.each do |t| %>
<div class="container">
  <p><%= i += 1 %>----</p>
  <p class="task"><%= link_to "#{t.title}", task_path(t) %></p>
  <p>---<%= t.completed? %></p>
</div>
<!-- <%= t.completed %> -->
<% end %>

<p id="new"><%= link_to "Create Task",  new_task_path%></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title%>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= @task.details %>
<%= @task.completed %>
<br>
<%= link_to 'edit', edit_task_path(@task) %>
<br>
<%= link_to 'home', tasks_path %>
<br>
<%= link_to 'delete', destroy_task_path(@task),  method: :delete, data: { confirm: 'are you sure?'} %>